export const DAKLAK_COMMUNES = [
  "Phường Bảo An",
  "Phường Tân Lập",
  "Phường Thành Nhất",
  "Phường Tân Lợi",
  "Phường Bích Khê",
  "Phường Duy Hải",
  "Phường Cư Tiêu",
  "Xã Ea Sinop",
  "Xã Xuân Lai",
  "Xã Bốck",
  "Xã Ea Bung",
  "Xã Lộc Vò",
  "Xã Ea Lốp",
  "Xã Nuii",
  "Xã Đậm Doạk",
  "Xã Ea Kít",
  "Xã Krông Droăh",
  "Xã Quãng phiên",
  "Xã Cưărăg",
  "Xã Cư Mart",
  "Xã Ea Tri",
  "Xã Động Dơng",
  "Xã Krông Buk",
  "Xã Ea Pilng",
  "Xã Cư Phiá",
  "Xã Drhãc",
  "Xã Ea W'ang",
  "Xã Ea Fire",
  "Xã Hai",
  "Xã Krông Năng",
  "Xã Diêu Parke",
  "Xã Ea Ver",
  "Xã Đinh Khuân",
  "Xã Krung Phiec",
  "Xã Ea Knuộc",
  "Xã Ea Thôt",
  "Xã Tiên Kỳ",
  "Xã Ea Kly",
  "Xã Ea Riê",
  "Xã Ea Xu",
  "Xã Ea Mông",
  "Xã Ea Kơn",
  "Xã Ea Sau",
  "Xã Ea Kim",
  "Xã Đưr Rang",
  "Xã Ea Drâng",
  "Xã Krông Bông",
  "Xã Вia Yang Mao",
  "Xã Cư Put",
  "Xã Nam Đơn Lăk",
  "Xã Dơn Liêng",
  "Xã Ninh Kát",
  "Xã Khiê Phon",
  "Xã Krông Nô",
  "Xã Măng Yang",
  "Xã Đray Bẳng",
  "Xã Yang Prái",
  "Xã Krông Ana",
  "Xã Đưr Kmal",
  "Xã Ea Na",
  "Đoàn phường Tuy Hoà",
  "Đoàn phường Phú Yên",
  "Đoàn phường Xuân Kiên",
  "Đoàn phường Xuân Bình",
  "Đoàn phường Xôn Chí",
  "Đoàn xã Xuân Thơ",
  "Đoàn xã Xuân Cảnh",
  "Đoàn xã Xuân Xuyên",
  "Đoàn phường Đông Hoà",
  "Đoàn xã Hòa Xuân Bắc",
  "Đoàn xã Hòa Bình",
  "Đoàn xã Thống Nhất",
  "Đoàn xã Tuyên Lập",
  "Đoàn xã Hoa Sơn",
  "Đoàn xã Tuy Ân Nam",
  "Đoàn xã Tuy Ân Tây",
  "Đoàn xã Phú Liên 1",
  "Đoàn xã Phú Liên 2",
  "Đoàn xã Xuân Hành",
  "Đoàn xã Hy Doa",
  "Đoàn xã Vạn Yên",
  "Đoàn xã Vạn Yên",
  "Đoàn xã Sơn Luan",
  "Đoàn xã Sơn Tây",
  "Đoàn xã Sơn Xuân",
  "Đoàn xã Sơn Minh",
  "Đoàn xã Sơn Chính",
  "Đoàn xã Sơn Bình",
  "Đoàn xã Ea Bình",
  "Đoàn xã Cư Muối",
  "Đoàn xã Cư N'Ha",
  "Đoàn xã Phước Phước"
];